import { prisma } from "@/lib/prisma"
import { completeSetup } from "@/app/actions/completeSetup";
import { CheckCircle, Copy } from "lucide-react";



export default async function TechSetupPage({ 
  params 
}: { 
  params: Promise<{ jobId: string }> 
}) {
  const { jobId } = await params;

  const job = await prisma.job.findUnique({
    where: { id: jobId },
    include: { 
      vehicle: { include: { client: true } },
      device: true 
    }
  });

  if (!job) return <div>Job not found</div>;

  return (
    <div className="max-w-4xl mx-auto">
      <h2 className="text-2xl font-bold text-gray-800 mb-6">Server Configuration</h2>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* LEFT: Read-Only Data (Source) */}
        <div className="space-y-6">
          <div className="bg-blue-50 p-6 rounded-xl border border-blue-100">
            <h3 className="text-blue-800 font-bold mb-4">Device Information</h3>
            
            <div className="mb-4">
              <label className="text-xs font-bold text-blue-400 uppercase">IMEI Number</label>
              <div className="flex items-center gap-2 bg-white p-3 rounded border border-blue-200 mt-1">
                <code className="text-xl font-mono text-gray-800 flex-1">{job.device?.imei}</code>
                <span className="text-xs text-gray-400 border px-2 py-1 rounded">Copy</span>
              </div>
            </div>

            <div className="mb-4">
              <label className="text-xs font-bold text-blue-400 uppercase">SIM Number</label>
              <div className="flex items-center gap-2 bg-white p-3 rounded border border-blue-200 mt-1">
                <code className="text-lg font-mono text-gray-800 flex-1">{job.device?.simNumber}</code>
              </div>
            </div>

            <div className="mb-4">
              <label className="text-xs font-bold text-blue-400 uppercase">Device Type</label>
              <p className="font-medium text-gray-700">{job.device?.type}</p>
            </div>
          </div>

          <div className="bg-gray-50 p-6 rounded-xl border">
             <h3 className="text-gray-600 font-bold mb-4">Vehicle Information</h3>
             <div className="grid grid-cols-2 gap-4">
                <div>
                  <span className="text-xs text-gray-400 block">Plate Number</span>
                  <span className="font-mono font-bold text-lg">{job.vehicle.plateNumber}</span>
                </div>
                <div>
                  <span className="text-xs text-gray-400 block">Model</span>
                  <span className="font-medium">{job.vehicle.name} {job.vehicle.year}</span>
                </div>
                <div className="col-span-2">
                  <span className="text-xs text-gray-400 block">Client Name</span>
                  <span className="font-medium">{job.vehicle.client.fullName}</span>
                </div>
             </div>
          </div>
        </div>

        {/* RIGHT: Action Form */}
        <div className="bg-white p-8 rounded-xl shadow-lg border h-fit">
          <h3 className="text-xl font-bold text-gray-800 mb-2">Confirm Online Status</h3>
          <p className="text-sm text-gray-500 mb-6">
            Configure the device on the tracking server first. Once it is reporting online, complete this form.
          </p>

          <form action={completeSetup} className="space-y-6">
            <input type="hidden" name="jobId" value={job.id} />

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Generated Platform ID (Server ID)</label>
              <input 
                name="platformId" 
                type="text" 
                placeholder="e.g. USER-10293 or 5543" 
                className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" 
              />
              <p className="text-xs text-gray-400 mt-1">Optional: ID generated by Traccar/Gurtam</p>
            </div>

            <div className="flex items-start gap-3 bg-yellow-50 p-4 rounded-lg text-yellow-800 text-sm">
              <input type="checkbox" required className="mt-1 h-4 w-4 text-blue-600" />
              <span>I confirm that I have verified the device is <b>Online</b> and reporting location data on the server.</span>
            </div>

            <button type="submit" className="w-full bg-black text-white font-bold py-4 rounded-xl hover:bg-gray-800 flex justify-center items-center gap-2 transition">
              <CheckCircle size={20} />
              Mark as Configured
            </button>
          </form>
        </div>

      </div>
    </div>
  );
}